### ISSUE TITLE
Error in transaction "Begin setup"

### ISSUE THREAD

**Issue by joesixpack** [avantgardefinance/melon-terminal#445]
Error: Timeout exceeded during the transaction confirmation process. Be aware the transaction could still get confirmed!
    at https://melon.avantgarde.finance/static/js/6.8205447f.chunk.js:2:1019834
    at c (https://melon.avantgarde.finance/static/js/6.8205447f.chunk.js:2:1622505)
    at Generator._invoke (https://melon.avantgarde.finance/static/js/6.8205447f.chunk.js:2:1622258)
    at Generator.forEach.e.<computed> [as next] (https://melon.avantgarde.finance/static/js/6.8205447f.chunk.js:2:1622862)
    at r (https://melon.avantgarde.finance/static/js/6.8205447f.chunk.js:2:1068005)
    at s (https://melon.avantgarde.finance/static/js/6.8205447f.chunk.js:2:1068216)

**Comment by fubhy** [comment]
Hey there. This means that you chose a gas price that was too low to make your transaction go through within the 15 minutes timeout limit. 

If you used metamask, you can speed up or cancel the transaction in MetaMask and try again with a higher gas price.

Alternatively, you can also simply wait til the transaction finally goes through and continue your fund setup process after refreshing your browser window.

We already have an open issue to remove the timeout and instead offer gas price increase / transaction cancellation.

#400
