### ISSUE TITLE
Error in transaction "Invest"

### ISSUE THREAD

**Issue by plutoegg** [avantgardefinance/melon-terminal#463]
Parameter|Value
------|-----
Contract|[0x1205c8acC24b29d0884f15D3417F7d63FEc92D96](https://etherscan.io/address/0x1205c8acC24b29d0884f15D3417F7d63FEc92D96)
Method|requestInvestment
Arguments|["11104590369014916210","10904876400000000000000","0xe41d2489571d322189246dafa5ebde1f4699f498"]
Sender|[0x05e3fddf871bcba3f0651fb01fd0d621ad087be2](https://etherscan.io/address/0x05e3fddf871bcba3f0651fb01fd0d621ad087be2)

Stack trace: InsufficientAllowanceError: Requested amount exceeds current allowance.
    at t.<anonymous> (https://melon.avantgarde.finance/static/js/6.84c512e4.chunk.js:2:3814061)
    at c (https://melon.avantgarde.finance/static/js/6.84c512e4.chunk.js:2:3387861)
    at Generator._invoke (https://melon.avantgarde.finance/static/js/6.84c512e4.chunk.js:2:3387614)
    at Generator.forEach.e.<computed> [as next] (https://melon.avantgarde.finance/static/js/6.84c512e4.chunk.js:2:3388218)
    at o (https://melon.avantgarde.finance/static/js/6.84c512e4.chunk.js:2:3808770)

**Comment by iherger** [comment]
Thanks for reporting this error.

It seems that the transaction was successful after all. 

Can you give us some more information on how this happened, and how it was resolved (so it seems...)?
