### ISSUE TITLE
Error in transaction "Invest"

### ISSUE THREAD

**Issue by iemwill** [avantgardefinance/melon-terminal#467]
Error message: Requested amount exceeds current allowance.
Fund: jizZ
URL: https://melon.avantgarde.finance/kovan/fund/0xB942acc51bfDb38303D15522c720d2b7245F5b8a/invest
Contract: [0x165BA7055719FaFA790a78caf69Cd32738001759](https://etherscan.io/address/0x165BA7055719FaFA790a78caf69Cd32738001759)
Method: requestInvestment
Arguments: ["1000000000000000000","1000000000000000000","0x4a1218C3BE387F11E9FEb0d6Eb61659D085b0589"]
Sender: [0xebe14e5e4ac71c91fccb65b99e1eee9a40b0482e](https://etherscan.io/address/0xebe14e5e4ac71c91fccb65b99e1eee9a40b0482e)
Connection: metamask
Network: KOVAN
Stack trace: InsufficientAllowanceError: Requested amount exceeds current allowance.
    at t.<anonymous> (https://melon.avantgarde.finance/static/js/6.4e90a44d.chunk.js:2:3814061)
    at c (https://melon.avantgarde.finance/static/js/6.4e90a44d.chunk.js:2:3387861)
    at Generator._invoke (https://melon.avantgarde.finance/static/js/6.4e90a44d.chunk.js:2:3387614)
    at Generator.forEach.e.<computed> [as next] (https://melon.avantgarde.finance/static/js/6.4e90a44d.chunk.js:2:3388218)
    at o (https://melon.avantgarde.finance/static/js/6.4e90a44d.chunk.js:2:3808770)

**Comment by iherger** [comment]
Thanks for reporting this.

Are you able to reproduce this consistently, or was this a one time error?

**Comment by iemwill** [comment]
This was a one time error i had with other funds too, after refreshing the page it allows me to click the button `execute request` and that works. 

But currently on Kovan there is no trading pair open...Whats up, does somebody know?

**Comment by iherger** [comment]
Closing this, as it seems to have been an irregular error.
