### ISSUE TITLE
Error in transaction "Take order on the Melon engine"

### ISSUE THREAD

**Issue by jennazenk** [avantgardefinance/melon-terminal#473]
Getting this error although I do have enough funds (+4eth) for the transaction gas 

Error message: Node error: "insufficient funds for gas * price   value"
Fund: AF MTC 4
URL: https://melon.avantgarde.finance/mainnet/fund/0x7A956B7C804039bD92Fbfd2b8034d5FbCC2d2d40/trade
Contract: [0xf82f6cBE25dF966183536956ADeEdEf63D0D0516](https://etherscan.io/address/0xf82f6cBE25dF966183536956ADeEdEf63D0D0516)
Method: callOnExchange
Arguments: ["0","takeOrder(address,address[8],uint256[8],bytes[4],bytes32,bytes)",["0x0000000000000000000000000000000000000000","0x0000000000000000000000000000000000000000","0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2","0xec67005c4e498ec7f55e092bd1d35cbc47c91892","0x0000000000000000000000000000000000000000","0x0000000000000000000000000000000000000000","0x0000000000000000000000000000000000000000","0x0000000000000000000000000000000000000000"],["1089415072853210","50000000000000000","0","0","0","0","50000000000000000","0"],["0x0000000000000000000000000000000000000000000000000000000000000000","0x0000000000000000000000000000000000000000000000000000000000000000","0x0000000000000000000000000000000000000000000000000000000000000000","0x0000000000000000000000000000000000000000000000000000000000000000"],"0x0000000000000000000000000000000000000000000000000000000000000000",[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]]
Sender: [0xb0Cd1c7D81c9A204d620aA2eE0Ec85777d4aD817](https://etherscan.io/address/0xb0Cd1c7D81c9A204d620aA2eE0Ec85777d4aD817)
Connection: frame
Network: MAINNET
Stack trace: Error: Node error: "insufficient funds for gas * price   value"
    at Function.value (https://melon.avantgarde.finance/static/js/6.1c2132c2.chunk.js:2:714773)
    at e.<anonymous> (https://melon.avantgarde.finance/static/js/6.1c2132c2.chunk.js:2:726443)
    at c (https://melon.avantgarde.finance/static/js/6.1c2132c2.chunk.js:2:7089818)
    at Generator._invoke (https://melon.avantgarde.finance/static/js/6.1c2132c2.chunk.js:2:7089571)
    at Generator.forEach.e.<computed> [as next] (https://melon.avantgarde.finance/static/js/6.1c2132c2.chunk.js:2:7090175)
    at r (https://melon.avantgarde.finance/static/js/6.1c2132c2.chunk.js:2:1048985)
    at s (https://melon.avantgarde.finance/static/js/6.1c2132c2.chunk.js:2:1049196)

**Comment by jennazenk** [comment]
Tried again and then did not get the error, weirdly

**Comment by iherger** [comment]
Closing this, seems to have been a one-off error.
