### ISSUE TITLE
Error in transaction "Deploy AssetWhitelist Contract"

### ISSUE THREAD

**Issue by pythonpete32** [avantgardefinance/melon-terminal#524]
Error message: Node error: "invalid address (arg=\"_target\", coderType=\"address\", value=undefined)"
Fund: xDAO
URL: https://melon.avantgarde.finance/mainnet/fund/0xE33a205f4D095750ae37D2D01fb3152455Cb9560/policies
Method: deploy
Arguments: [["0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2","0xec67005c4e498ec7f55e092bd1d35cbc47c91892","0x960b236A07cf122663c4303350609A66A7B288C0","0x0d8775f648430679a709e98d2b0cb6250d2887ef","0x6b175474e89094c44da98b954eedeac495271d0f","0xdd974d5c2e2928dea5f71b9825b8b646686bd200","0x514910771af9ca656af840dff83e8264ecf986ca","0x0f5d2fb29fb7d3cfee444a200298f468908cc942","0x9f8f72aa9304c8b593d555f12ef6589cc3a579a2","0x1985365e9f78359a9B6AD760e32412f4a445E862","0x408e41876cccdc0f92210600ef50372656052a38","0x607F4C5BB672230e8672085532f7e901544a7375","0x89d24a6b4ccb1b6faa2625fe562bdd9a23260359","0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48","0x2260fac5e5542a773aa44fbcfedf7c193bc2c599","0xe41d2489571d322189246dafa5ebde1f4699f498"]]
Sender: [0x0f10f27fbE3622e7d4BdF1f141c6E50Ed8845AF6](https://etherscan.io/address/0x0f10f27fbE3622e7d4BdF1f141c6E50Ed8845AF6)
Connection: frame
Network: MAINNET
Stack trace: Error: Node error: "invalid address (arg=\"_target\", coderType=\"address\", value=undefined)"
    at Function.value (https://melon.avantgarde.finance/static/js/6.d5e64fcf.chunk.js:2:714773)
    at e.<anonymous> (https://melon.avantgarde.finance/static/js/6.d5e64fcf.chunk.js:2:726443)
    at c (https://melon.avantgarde.finance/static/js/6.d5e64fcf.chunk.js:2:7089950)
    at Generator._invoke (https://melon.avantgarde.finance/static/js/6.d5e64fcf.chunk.js:2:7089703)
    at Generator.forEach.e.<computed> [as next] (https://melon.avantgarde.finance/static/js/6.d5e64fcf.chunk.js:2:7090307)
    at r (https://melon.avantgarde.finance/static/js/6.d5e64fcf.chunk.js:2:1048983)
    at s (https://melon.avantgarde.finance/static/js/6.d5e64fcf.chunk.js:2:1049194)

**Comment by iherger** [comment]
Thanks for reporting.

Does this error persist, or have you been able to deploy that asset whitelist contract in the meantime?

I am not able to reproduce this locally, and I am looking for some more pointers to the problem. So if you have any additional information, please let me know.
