### ISSUE TITLE
Error in transaction "Execute investment request"

### ISSUE THREAD

**Issue by amadeobrands** [avantgardefinance/melon-terminal#528]
Error message: No investment request found.
Fund: ON DeFi
URL: https://melon.avantgarde.finance/mainnet/fund/0xD4020d2a03aA5a897A261c9549e36fAE18766fB3/invest
Contract: [0xD71A5Aed370BaDCA524b1dd8a62506e5dcA0e113](https://etherscan.io/address/0xD71A5Aed370BaDCA524b1dd8a62506e5dcA0e113)
Method: executeRequestFor
Arguments: ["0x2482dc04ac628a4b2700c071bfee557fd86c91ea"]
Sender: [0x2482dc04ac628a4b2700c071bfee557fd86c91ea](https://etherscan.io/address/0x2482dc04ac628a4b2700c071bfee557fd86c91ea)
Connection: metamask
Network: MAINNET
Stack trace: NoInvestmentRequestError: No investment request found.
    at t.<anonymous> (https://melon.avantgarde.finance/static/js/6.d5e64fcf.chunk.js:2:3787199)
    at c (https://melon.avantgarde.finance/static/js/6.d5e64fcf.chunk.js:2:3360250)
    at Generator._invoke (https://melon.avantgarde.finance/static/js/6.d5e64fcf.chunk.js:2:3360003)
    at Generator.forEach.e.<computed> [as next] (https://melon.avantgarde.finance/static/js/6.d5e64fcf.chunk.js:2:3360607)
    at o (https://melon.avantgarde.finance/static/js/6.d5e64fcf.chunk.js:2:3781340)

**Comment by iherger** [comment]
Thanks or reporting this.

This is probably due to a front-running issue: when you execute an investment request, you are receiving the incentive of 0.01 ETH back, that you provided when submitting the investment request. So when you try to execute your investment request, somebody else has already executed it (with a tiny amount gas more than you). 

In summary: your investment request has been executed by somebody else.

We are working on making the user experience better for this phenomenon.
