### ISSUE TITLE
Error accessing to fund "Admin" page

### ISSUE THREAD

**Issue by Cryptojuju** [avantgardefinance/melon-terminal#583]
Regardless of browser and tentative to refresh the page, the Admin menu doesn't display correctly ! 

RangeError: Invalid time value
    at Q (https://melon.avantgarde.finance/static/js/8.171b277c.chunk.js:2:6988198)
    at u (https://melon.avantgarde.finance/static/js/main.2bb7b771.chunk.js:1:83571)
    at Ki (https://melon.avantgarde.finance/static/js/8.171b277c.chunk.js:2:2697205)
    at ys (https://melon.avantgarde.finance/static/js/8.171b277c.chunk.js:2:2743611)
    at uc (https://melon.avantgarde.finance/static/js/8.171b277c.chunk.js:2:2736144)
    at sc (https://melon.avantgarde.finance/static/js/8.171b277c.chunk.js:2:2736069)
    at Xs (https://melon.avantgarde.finance/static/js/8.171b277c.chunk.js:2:2733078)
    at https://melon.avantgarde.finance/static/js/8.171b277c.chunk.js:2:2684463
    at t.unstable_runWithPriority (https://melon.avantgarde.finance/static/js/8.171b277c.chunk.js:2:2760045)
    at Ha (https://melon.avantgarde.finance/static/js/8.171b277c.chunk.js:2:2684172)

**Comment by fubhy** [comment]
Thanks for the report. This should be fixed now.
