### ISSUE TITLE
General error "TypeError"

### ISSUE THREAD

**Issue by TobWag96** [avantgardefinance/melon-terminal#601]
TypeError: Cannot read property 'map' of undefined
    at https://melon.avantgarde.finance/static/js/15.56cf3f76.chunk.js:1:22544
    at Object.po [as useMemo] (https://melon.avantgarde.finance/static/js/8.a68642ff.chunk.js:2:2707934)
    at Object.t.useMemo (https://melon.avantgarde.finance/static/js/8.a68642ff.chunk.js:2:2645877)
    at ie (https://melon.avantgarde.finance/static/js/15.56cf3f76.chunk.js:1:22445)
    at Ki (https://melon.avantgarde.finance/static/js/8.a68642ff.chunk.js:2:2704268)
    at No (https://melon.avantgarde.finance/static/js/8.a68642ff.chunk.js:2:2713172)
    at ys (https://melon.avantgarde.finance/static/js/8.a68642ff.chunk.js:2:2751910)
    at uc (https://melon.avantgarde.finance/static/js/8.a68642ff.chunk.js:2:2743207)
    at sc (https://melon.avantgarde.finance/static/js/8.a68642ff.chunk.js:2:2743132)
    at Xs (https://melon.avantgarde.finance/static/js/8.a68642ff.chunk.js:2:2740141)

**Comment by iherger** [comment]
Closing this in favour of #613
