### ISSUE TITLE
General error "TypeError"

### ISSUE THREAD

**Issue by LautaroParada** [avantgardefinance/melon-terminal#605]
TypeError: Cannot read property 'map' of undefined
    at se (https://melon.avantgarde.finance/static/js/4.315f4b0b.chunk.js:1:20536)
    at Ki (https://melon.avantgarde.finance/static/js/8.9e26cd25.chunk.js:2:2704268)
    at No (https://melon.avantgarde.finance/static/js/8.9e26cd25.chunk.js:2:2713172)
    at ys (https://melon.avantgarde.finance/static/js/8.9e26cd25.chunk.js:2:2751910)
    at uc (https://melon.avantgarde.finance/static/js/8.9e26cd25.chunk.js:2:2743207)
    at sc (https://melon.avantgarde.finance/static/js/8.9e26cd25.chunk.js:2:2743132)
    at Xs (https://melon.avantgarde.finance/static/js/8.9e26cd25.chunk.js:2:2740141)
    at https://melon.avantgarde.finance/static/js/8.9e26cd25.chunk.js:2:2691526
    at t.unstable_runWithPriority (https://melon.avantgarde.finance/static/js/8.9e26cd25.chunk.js:2:2767108)
    at Ha (https://melon.avantgarde.finance/static/js/8.9e26cd25.chunk.js:2:2691235)

**Comment by iherger** [comment]
Closing in favour of #613
