### ISSUE TITLE
General error "TypeError"

### ISSUE THREAD

**Issue by warrenjk** [avantgardefinance/melon-terminal#608]
I pasted this link into Safari and into Brave on my MacBookPro running Mojave OS v10.14.6
https://melon.avantgarde.finance/
The page expected shows briefly and then converts to an error message.
As requested, I am reporting that error.

TypeError: Cannot read property 'filter' of undefined
    at Pe (https://melon.avantgarde.finance/static/js/13.d7847bc3.chunk.js:1:27280)
    at Ki (https://melon.avantgarde.finance/static/js/8.98ac616d.chunk.js:2:2706844)
    at No (https://melon.avantgarde.finance/static/js/8.98ac616d.chunk.js:2:2715748)
    at ys (https://melon.avantgarde.finance/static/js/8.98ac616d.chunk.js:2:2754486)
    at uc (https://melon.avantgarde.finance/static/js/8.98ac616d.chunk.js:2:2745783)
    at sc (https://melon.avantgarde.finance/static/js/8.98ac616d.chunk.js:2:2745708)
    at Xs (https://melon.avantgarde.finance/static/js/8.98ac616d.chunk.js:2:2742717)
    at https://melon.avantgarde.finance/static/js/8.98ac616d.chunk.js:2:2694102
    at t.unstable_runWithPriority (https://melon.avantgarde.finance/static/js/8.98ac616d.chunk.js:2:2769684)
    at Ha (https://melon.avantgarde.finance/static/js/8.98ac616d.chunk.js:2:2693811)

Please fix or advise.

**Comment by iherger** [comment]
We currently have an outage of the subgraph server, I am afraid. We hope that this is fixed soon by the team of thegraph.com

**Comment by iherger** [comment]
The subgraph server seems to be working again. Can you try again and see if it works now?
