### ISSUE TITLE
General error "TypeError"

### ISSUE THREAD

**Issue by hmmmason** [avantgardefinance/melon-terminal#617]
TypeError: Cannot read property 'filter' of undefined
    at Pe (https://melon.avantgarde.finance/static/js/13.c8c7e867.chunk.js:1:27280)
    at Ki (https://melon.avantgarde.finance/static/js/8.c11c7dea.chunk.js:2:2706844)
    at No (https://melon.avantgarde.finance/static/js/8.c11c7dea.chunk.js:2:2715748)
    at ys (https://melon.avantgarde.finance/static/js/8.c11c7dea.chunk.js:2:2754486)
    at uc (https://melon.avantgarde.finance/static/js/8.c11c7dea.chunk.js:2:2745783)
    at sc (https://melon.avantgarde.finance/static/js/8.c11c7dea.chunk.js:2:2745708)
    at Xs (https://melon.avantgarde.finance/static/js/8.c11c7dea.chunk.js:2:2742717)
    at https://melon.avantgarde.finance/static/js/8.c11c7dea.chunk.js:2:2694102
    at t.unstable_runWithPriority (https://melon.avantgarde.finance/static/js/8.c11c7dea.chunk.js:2:2769684)
    at Ha (https://melon.avantgarde.finance/static/js/8.c11c7dea.chunk.js:2:2693811)

**Comment by iherger** [comment]
On which page did you have this error?

**Comment by hmmmason** [comment]
https://melon.avantgarde.finance/
___

*Mason Vollum*
*mason.vollum@gmail.com <mason.vollum@gmail.com>*
6122405816

**Comment by iherger** [comment]
Closing this in favour of #613
