### ISSUE TITLE
General error "TypeError"

### ISSUE THREAD

**Issue by CyberKingDavid** [avantgardefinance/melon-terminal#629]
TypeError: Cannot read property 'monthToDate' of undefined
    at https://melon.avantgarde.finance/static/js/12.5bf44433.chunk.js:1:44533
    at Object.po [as useMemo] (https://melon.avantgarde.finance/static/js/8.169ff604.chunk.js:2:2710510)
    at Object.t.useMemo (https://melon.avantgarde.finance/static/js/8.169ff604.chunk.js:2:2648453)
    at ot (https://melon.avantgarde.finance/static/js/12.5bf44433.chunk.js:1:44433)
    at Ki (https://melon.avantgarde.finance/static/js/8.169ff604.chunk.js:2:2706844)
    at No (https://melon.avantgarde.finance/static/js/8.169ff604.chunk.js:2:2715748)
    at ys (https://melon.avantgarde.finance/static/js/8.169ff604.chunk.js:2:2754486)
    at uc (https://melon.avantgarde.finance/static/js/8.169ff604.chunk.js:2:2745783)
    at sc (https://melon.avantgarde.finance/static/js/8.169ff604.chunk.js:2:2745708)
    at Xs (https://melon.avantgarde.finance/static/js/8.169ff604.chunk.js:2:2742717)

**Comment by iherger** [comment]
This should be fixed now.
